# Default values for cells.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pydio/cells
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: unstable

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "app"

podAnnotations: {
  "vault.hashicorp.com/agent-inject": "true",
  "vault.hashicorp.com/role": "app",
  "vault.hashicorp.com/agent-init-first": "true",
  "vault.hashicorp.com/agent-inject-token": "true"
}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 8080
  discoveryPort: 8002
  binds:
    # Set values here if you want to bind the port elsewhere
  reverseproxyurl:
  tlsconfig:
    selfsigned:

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: cells-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  #tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

#------------------------------
# Dependency settings
#------------------------------
mariadb:
  enabled: true
  volumePermissions:
    enabled: true

redis:
  enabled: true
  volumePermissions:
    enabled: true
  auth:
    enabled: false

nats:
  enabled: true
  auth:
    enabled: false
  volumePermissions:
    enabled: true

etcd:
  enabled: true
  auth:
    rbac:
      create: false
  volumePermissions:
    enabled: true

minio:
  enabled: true
  defaultBuckets: "thumbnails pydiods1 personal versions cellsdata binaries"
  volumePermissions:
    enabled: true

mongodb:
  enabled: true
  auth: 
    enabled: false
  volumePermissions:
    enabled: true

vault:
  enabled: true
  injector:
    annotations: {
      "helm.sh/hook": "pre-install",
      "helm.sh/hook-weight": "-1"
    }
    webhook:
      annotations: {
        "helm.sh/hook": "pre-install",
        "helm.sh/hook-weight": "-1"
      }
      failurePolicy: Fail
      namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["vault","kube-system","kube-public","kube-node-lease"]
  server:
    annotations: {
      "helm.sh/hook": "pre-install",
      "helm.sh/hook-weight": "-1"
    }
    dataStorage:
      mountPath: /tmp/vault/data
    extraVolumes:
    - type: configMap
      name: cells-vault
    postStart:
    - "/bin/sh"
    - "-c"
    - "sleep 5 && cp /vault/userconfig/cells-vault/bootstrap.sh /tmp/bootstrap.sh && chmod +x /tmp/bootstrap.sh && /tmp/bootstrap.sh"
  statefulset:
    annotations: {
      "helm.sh/hook": "pre-install",
      "helm.sh/hook-weight": "-1"
    }
